version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - http_proxy=http://10.160.3.88:8080
      - https_proxy=http://10.160.3.88:8080
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    networks:
      - ollama_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ollama:

networks:
  ollama_network:
    driver: bridge
